name: Deploy Frontend

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./package
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14.x'

      - name: Install
        run: |
          yarn
      - name: Build
        run: |
          yarn build
      - name: Publish
        run: |
          yarn npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
